/** main */
export const SET_INPUT_VALUE = "SET_INPUT_VALUE";
export const SET_CURR_PAGE = "SET_CURR_PAGE";
export const SET_SCROLL_LOADING = "SET_SCROLL_LOADING";
export const SET_FETCH_DATA_LOADING = "SET_FETCH_DATA_LOADING";
export const SET_FILTERED_CONTACTS = "SET_FILTERED_CONTACTS";
